---
title: "My First Project"
author: "Joshua Matamoros"
date: "2026-8-20"
categories: [project,general]
---

```         
```

A rapidly growing problem has been Earths environmental change. More specifically, the tremendous change in the Arctic for the past decades. To understand the rate and severity at which the Arctic is losing its sea ice, a 16 year long project was conducted, recording data every 30 minutes from 2006-2022.

What data does this study record exactly, though?

The melting of the ice is becoming exponentially quicker. Within the study, the amount of sunlight which was captured a certain distance beneath the surface of water was recorded. It is likely for one to hypothesize throughout the 16 years, the amount of sunlight which was recorded obviously increased due to the reduction of ice in each passing year.

Along with the amount of sunlight being recorded, the temperature of the water was as well being recorded. Like the sunlight, it seems reasonable to assume that the temperature was to increase. Even if the difference seems minimal, the data set is only being taken from a 16 year sample, which is small relative to how long global warming has been affecting Earth.
